cells:
  temperatura:
    dataRef: serie-temperatura
    label:
      units: "°C"
      decimalPoints: 1
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "blue", level: 0}
        - {color: "orange", level: 25}
        - {color: "red", level: 35}
